In [ ]:
import torch

In [ ]:
print(torch.__version__)

2.11.0+cu128


In [ ]:
!nvidia-smi

Mon Sep 21 05:25:50 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   48C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

# Tensors

In [ ]:
# scalar
scalar = torch.tensor(1)
scalar

tensor(1)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

1

In [ ]:
# vector
vector = torch.tensor([1,2])
vector

tensor([1, 2])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# matrix
matrix = torch.tensor([[1,2],[3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [ ]:
matrix.ndim, matrix.dtype

(2, torch.int64)

In [ ]:
matrix[1]

tensor([3, 4])

In [ ]:
matrix.shape

torch.Size([2, 2])

# Random tensors

In [ ]:
tensor = torch.rand(3,4)
tensor

tensor([[0.1705, 0.4073, 0.4692, 0.5951],
        [0.6014, 0.9285, 0.6583, 0.4989],
        [0.1794, 0.7859, 0.3293, 0.2920]])

In [ ]:
iamge = torch.rand(3,300,300)
iamge.ndim, iamge.shape, iamge.dtype

(3, torch.Size([3, 300, 300]), torch.float32)

# Zeros and ones

In [ ]:
zeros = torch.zeros(3,4)
ones = torch.ones(3,4)
zeros, ones

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [ ]:
zeros.dtype, ones.dtype

(torch.float32, torch.float32)

# Ranges and tensors-like

In [ ]:
rng = torch.arange(1,10,2)
rng

tensor([1, 3, 5, 7, 9])

In [ ]:
rng.ndim

1

In [ ]:
torch.zeros_like(rng)

tensor([0, 0, 0, 0, 0])

# Datatypes

In [ ]:
tensor = torch.tensor([1,2,3],dtype=None,device=None,requires_grad=False)
tensor.dtype, tensor.device

(torch.int64, device(type='cpu'))

In [ ]:
tensor.type(torch.float64).dtype

torch.float64

In [ ]:
tensor_u8 = torch.tensor([1,2,3],dtype=torch.uint8,device="cpu",requires_grad=False)
tensor_u8.dtype

torch.uint8

In [ ]:
res = tensor_u8 * tensor
res, res.dtype

(tensor([1, 4, 9]), torch.int64)

In [ ]:
tensor_f64 = torch.tensor([1,2,3],dtype=torch.float64,device="cpu",requires_grad=False)
tensor_f64.dtype

torch.float64

In [ ]:
res = tensor_f64 * tensor
res, res.dtype

(tensor([1., 4., 9.], dtype=torch.float64), torch.float64)

# Operations

In [ ]:
tensor = torch.tensor([1,2,3])

In [ ]:
tensor + 1

tensor([2, 3, 4])

In [ ]:
tensor * 2

tensor([2, 4, 6])

In [ ]:
tensor > 2

tensor([False, False,  True])

In [ ]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
tensor * tensor

tensor([1, 4, 9])

## Matrix multiplication

In [ ]:
tensor.matmul(tensor), 1*1+2*2+3*3, tensor @ tensor

(tensor(14), 14, tensor(14))

In [ ]:
%%time
tensor.matmul(tensor)

CPU times: user 584 µs, sys: 0 ns, total: 584 µs
Wall time: 538 µs


tensor(14)

In [ ]:
%%time
1*1+2*2+3*3

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 5.72 µs


14

In [ ]:
%%time
value = 0
for i in rng(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 1.88 ms, sys: 0 ns, total: 1.88 ms
Wall time: 4.43 ms


tensor(14)

In [ ]:
# Matix multiplication
#  Inner dimensions must match
#  The resulting matrix has the shape of the outer dimensions
torch.rand(3,2) @ torch.rand(2,4)

tensor([[0.2845, 0.6237, 0.3685, 0.3742],
        [0.8256, 1.5833, 1.0284, 0.9798],
        [0.7319, 1.4094, 0.9127, 0.8713]])

In [ ]:
# Transpose
torch.rand(3,2).mm(torch.rand(3,2).T)

tensor([[0.9984, 0.6928, 1.1675],
        [0.4975, 0.4992, 0.5597],
        [1.1991, 1.1015, 1.3636]])

## Aggregation

In [ ]:
tensor = torch.arange(0,100,10)
tensor

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
tensor.min(), torch.min(tensor)

(tensor(0), tensor(0))

In [ ]:
tensor.max()

tensor(90)

In [ ]:
tensor.type(torch.float).mean(), tensor.mean(dtype=torch.float), tensor.mean(dtype=torch.float).dtype

(tensor(45.), tensor(45.), torch.float32)

In [ ]:
tensor.median()

tensor(40)

In [ ]:
tensor.sum()

tensor(450)

In [ ]:
tensor.argmax()

tensor(9)

In [ ]:
tensor.argmin()

tensor(0)

# Tensor shape

## Reshape

In [ ]:
tensor = torch.arange(0,100,10)
tensor, tensor.shape, tensor.ndim

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.Size([10]), 1)

In [ ]:
tensor = tensor.reshape(10)
tensor, tensor.shape, tensor.ndim

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.Size([10]), 1)

In [ ]:
tensor = tensor.reshape(1,10)
tensor, tensor.shape, tensor.ndim

(tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]]), torch.Size([1, 10]), 2)

In [ ]:
tensor = tensor.reshape(2,5)
tensor, tensor.shape, tensor.ndim

(tensor([[ 0, 10, 20, 30, 40],
         [50, 60, 70, 80, 90]]),
 torch.Size([2, 5]),
 2)

In [ ]:
tensor = tensor.reshape(10,1)
tensor, tensor.shape, tensor.ndim

(tensor([[ 0],
         [10],
         [20],
         [30],
         [40],
         [50],
         [60],
         [70],
         [80],
         [90]]),
 torch.Size([10, 1]),
 2)

In [ ]:
tensor = tensor.reshape(1,2,5)
tensor, tensor.shape, tensor.ndim

(tensor([[[ 0, 10, 20, 30, 40],
          [50, 60, 70, 80, 90]]]),
 torch.Size([1, 2, 5]),
 3)

## View

In [ ]:
tensor_v = tensor.view(10,1)
tensor_v, tensor_v.shape, tensor_v.ndim

(tensor([[ 0],
         [10],
         [20],
         [30],
         [40],
         [50],
         [60],
         [70],
         [80],
         [90]]),
 torch.Size([10, 1]),
 2)

In [ ]:
tensor[:,:,2]=99
tensor, tensor_v

(tensor([[[ 0, 10, 99, 30, 40],
          [50, 60, 99, 80, 90]]]),
 tensor([[ 0],
         [10],
         [99],
         [30],
         [40],
         [50],
         [60],
         [99],
         [80],
         [90]]))

# Stack

In [ ]:
tensor = torch.arange(0,100,10)
torch.stack([tensor,tensor])

tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [ ]:
torch.stack([tensor,tensor],dim=1)

tensor([[ 0,  0],
        [10, 10],
        [20, 20],
        [30, 30],
        [40, 40],
        [50, 50],
        [60, 60],
        [70, 70],
        [80, 80],
        [90, 90]])

In [ ]:
torch.vstack([tensor,tensor])

tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [ ]:
torch.hstack([tensor,tensor])

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90,  0, 10, 20, 30, 40, 50, 60, 70,
        80, 90])

In [ ]:
torch.stack([tensor,tensor+1],dim=-2)

tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]])

## Squeeze

In [ ]:
tensor = torch.arange(0,100,10)
tensor = tensor.reshape(1,10)
tensor, tensor.shape, tensor.ndim

(tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]]), torch.Size([1, 10]), 2)

In [ ]:
tensor = tensor.squeeze()
tensor, tensor.shape, tensor.ndim

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.Size([10]), 1)

In [ ]:
tensor = tensor.unsqueeze(1)
tensor, tensor.shape, tensor.ndim

(tensor([[ 0],
         [10],
         [20],
         [30],
         [40],
         [50],
         [60],
         [70],
         [80],
         [90]]),
 torch.Size([10, 1]),
 2)

In [ ]:
tensor = tensor.unsqueeze(0)
tensor, tensor.shape, tensor.ndim

(tensor([[[ 0],
          [10],
          [20],
          [30],
          [40],
          [50],
          [60],
          [70],
          [80],
          [90]]]),
 torch.Size([1, 10, 1]),
 3)

## Permute

In [ ]:
tensor = torch.arange(0,100,10)
tensor = tensor.reshape(1,10)
tensor, tensor.shape, tensor.ndim

(tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]]), torch.Size([1, 10]), 2)

In [ ]:
tensor.permute(1,0)

tensor([[ 0],
        [10],
        [20],
        [30],
        [40],
        [50],
        [60],
        [70],
        [80],
        [90]])

In [ ]:
tensor_v = tensor.permute(1,0)
tensor[:,2]=99
tensor, tensor_v

(tensor([[ 0, 10, 99, 30, 40, 50, 60, 70, 80, 90]]),
 tensor([[ 0],
         [10],
         [99],
         [30],
         [40],
         [50],
         [60],
         [70],
         [80],
         [90]]))

# Indexing

In [ ]:
tensor = torch.arange(1,10).reshape(1,3,3)
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
tensor[0,0]

tensor([1, 2, 3])

In [ ]:
tensor[0][0][0]

tensor(1)

In [ ]:
tensor[:,:,0]

tensor([[1, 4, 7]])

In [ ]:
tensor[:,:,:1]

tensor([[[1],
         [4],
         [7]]])

In [ ]:
tensor[:,:,:2]

tensor([[[1, 2],
         [4, 5],
         [7, 8]]])

# Numpy

In [ ]:
import numpy as np

In [ ]:
array = np.arange(1,10)
tensor = torch.from_numpy(array)
array, tensor, tensor.dtype

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 torch.int64)

In [ ]:
array = np.arange(1.0,10.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [ ]:
array += 1
array, tensor

(array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float64))

In [ ]:
array = array + 1
array, tensor

(array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]),
 tensor([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float64))

In [ ]:
tensor = torch.ones(10)
array = tensor.numpy()
tensor, array

(tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor += 1
tensor, array

(tensor([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]),
 array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.], dtype=float32))

In [ ]:
tensor = tensor + 1
tensor, array

(tensor([4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]),
 array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.], dtype=float32))

# Reproducibility

In [ ]:
torch.manual_seed(42)
a = torch.rand(3)
torch.manual_seed(42)
b = torch.rand(3)
a == b

tensor([True, True, True])

# GPU

In [ ]:
torch.cuda.is_available()

True

In [ ]:
torch.cuda.device_count()

1

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
tensor = torch.tensor([1,2,3])
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [ ]:
tensor = tensor.to(device)
tensor, tensor.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

In [ ]:
# numpy doesn't work in gpu
tensor.cpu().numpy()

array([1, 2, 3])